version: '3.8'
services:
  postgres_sixpport:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sixpport_dev
      POSTGRES_DB: sixpport_ops
    ports:
      - "5432:5432"
    volumes:
      # Esto ejecuta la creación de tablas automáticamente
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

      